### ISSUE TITLE
Peer review onderzoeksvraag Jordy

### ISSUE THREAD

**Issue by jor-s** [ralfz123/functional-programming#2]
Leuke onderzoeksvraag! Ik vind jouw assumptie ook wel sterk staan. Ik zou precies hetzelfde hierover denken. Het is ook nice dat je je onderzoeksvraag op dezelfde pagina als jouw eerste inzichten hebt geplaatst. Zo kan ik zien hoe je aan jouw onderzoeksvraag bent gekomen. Als feedback heb ik dat je een kopje kan toevoegen waarin je laat zien welke data je nodig hebt. Zo weet de lezer welke data je gaat gebruiken om je onderzoeksvraag te beantwoorden.

**Comment by ralfz123** [comment]
Welke vragen komen in jou op bij mijn onderzoeksvraag @sahitj001?

En heb je niet gezien dat ik de data in deze pagina heb staan? Dat is [hier](https://github.com/ralfz123/functional-programming/wiki/Onderzoek-%F0%9F%94%8D#data) te vinden. (Staat onderaan de assumpties)

**Comment by jor-s** [comment]
My bad.. Ik heb de pages dropdown niet geklikt, ik keek naar de weken..
![ZrH2meF](https://user-images.githubusercontent.com/10923626/97440705-182e3600-1928-11eb-807d-c52b39d0c9fe.png)

Ik kan je zo wel nog een keer feedback geven als jij dat nog wil.

**Comment by jor-s** [comment]
Ik keek naar 'eerste inzichten'

**Comment by ralfz123** [comment]
Je moet beginnen bij mijn Readme ;). Daar staat een link naar de Onderzoek-pagina

**Comment by jor-s** [comment]
Ik zal na de college van Robert jou weer feedback geven!
