### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by RowinRuizendaal** [ralfz123/functional-programming#3]
Suggestions:

#### Research question

Your research questions are looking good, they are completely different, the crime rates one seems interesting to me, but I am not entirely sure if you can find a dataset about that one. Also, did you picked one out of the list? If so which one did you took out? Or are you still in doubt of which one to pick? I assume you picked the parking spots for electric cars (looking at the assumptions)

#### Assumptions

I agree with your assumption, maybe you can split that one assumption into two assumptions?

```js
1. Ik denk dat het voor bestuurders van elektrische auto's in de stad het erg moeilijk wordt gemaakt. Ik denk dat als je meer in het centrum woont, dat je dan meer parkeergebieden hebt met oplaadpunten dan dat je verder van het centrum vandaan woont

2. In de avond zal het drukker op de parkeergebieden voor elektrische bestuurders zijn, omdat dan iedereen zijn auto wil opladen.
```
Are you only looking for data if you are living in a city such as (Amsterdam, Rotterdam, etc), or are you also going to find data for the smaller ones? The smaller ones can also have a Charging station in front of their house.

#### Sub questions

Looking great, I think you have a good image of what you want to research and how you are going to do that, by using these subquestions it is easier to make it into a coding program, maybe you can even make a filter with these subquestions where a visitor can see how expensive it is for electric car users, etc.

#### Datasets needed

Datasets are looking good, maybe document it for yourself where you can merge the two different datasets together, as in primary keys, I think you are going to use AreadId or something similar to that? (what do the different datasets have in common in their data such as column names etc.)

Keep it up, hopefully, my feedback is something useful (☞ﾟヮﾟ)☞☜(ﾟヮﾟ☜)

**Comment by ralfz123** [comment]
Nice feedback, thanks man! :) 

Een klein dingetje;

'_maybe you can even make a **filter** with these subquestions where a visitor can see how expensive it is for electric car users, etc._'

Je bedoelt met filter als in een filter maken in de dataviz? Of deelvragen filteren?

**Comment by RowinRuizendaal** [comment]
> 
> 
> Nice feedback, thanks man! :)
> 
> Een klein dingetje;
> 
> '_maybe you can even make a **filter** with these subquestions where a visitor can see how expensive it is for electric car users, etc._'
> 
> Je bedoelt met filter als in een filter maken in de dataviz? Of deelvragen filteren?

Ik bedoel inderdaad een filter maken in de dataviz, die nieuwe inzicht(en)kunnen tonen als in visualisaties of dergelijke.

༼ つ ◕_◕ ༽つ

**Comment by ralfz123** [comment]
Allright man, thanks voor het duidelijke antwoord!
