### ISSUE TITLE
peerReview - 29oct

### ISSUE THREAD

**Issue by davidvanr21** [ralfz123/functional-programming#4]
This is a peer-review on the work that Ralf has done so far. I'm less strong in code so I will check the code, but mainly focus the review on the concept and other aspects. So let;s go!

# Repo & ReadME
Overall it looks pretty good and clear. Some things you've done pretty well are; added an ignore file to hide private data, no junkfiles included, 

Some things I've seen you maybe can adjust a little bit:
- Project where I use D3 for datavisualization for de Volkskrant > Change your description to something that is a bit more clear for a random visitor. Maybe something like: Project where I'm practising data visualisation for _de Volkskrant_ as client, using d3, JavaScript and more.
- Add your sub-questions to your ReadMe.

# Wiki
Your Wiki looks very good! The things that catch my eyes are written below. Let me know if I've said something weird or thought wrong about some particular part.

- The Homepage of your Wiki maybe can include something like an intro to the subject and have links to your other pages.
- Do you have something like a logbook? Can't find it in the Wiki, but maybe you want to keep that part private?

## Week 1
- You debrief does not exactly describes the case that is been given by de Volkskrant. Maybe try to make one line with the challenge they gave you to solve. Something like: De Volkskrant heeft mij de opdracht gegeven om een interessante datavisualisatie te maken rondom het onderwep "Auto's in de stad".
- Your workflow is well described. Maybe add of it is working well or that you are struggling with things.

## Week 2 - Research 
_[Link](https://github.com/ralfz123/functional-programming/wiki/Onderzoek-%F0%9F%94%8D)_

You've found very good datasets! Well done. It's very smart that you described the datasets so you can find them back easily.

- The image of the top mindmap is not very clear.
- "Is het druk in de parkeergebieden?" Which areas do you mean?
- Give a link to Stan his GitHub for example for the credits. Then people will know who "Stan" is ;)
- Make sure you sketch your ideas clear for yourself. You've got great ideas so it could become something really nice.

**Comment by ralfz123** [comment]
Thank David! Ik heb kritisch naar je feedback gekeken en zeker verwerkt.
