### ISSUE TITLE
Peer Review exercise Rowin

### ISSUE THREAD

**Issue by RowinRuizendaal** [ralfz123/functional-programming#5]
## Scan the repo + readme
- [x] gitignore is in the repo
- [ ] No node_modules or other junk found (besides wiki that was pushed by mistake 😀)
- [ ] Repo description is there I am just missing a few things what this project is and does etc. (template text atm)
- [ ] The concept described in readme. The research question is in the readme, data to be used is in the readme, a sketch of data visualization (missing). 
- [ ] Data is described properly, you are just missing that you are doing with invalid and empty values
- [x] I could find a link to the functional pattern but the page is empty? (Not sure if that is the right one)
- [x] Acknowledgments are there (nice 😬)

## Read the wiki
- [x] Debrief is documented in the wiki
- [ ] Data cleaning is documented, the transform data process is there but it is currently empty, assuming you need time :)
- [ ] Functional patterns that are being used is missing in the documentation
- [x] Improvements are documented (Well done, seeing some cool and interesting learning skills)

## Read the code linked in the wiki
- [x] The code flow is easy to understand, comments are helpful to understand the code
- [x] The code is good, first, you have some setup variables and then you are calling a function with these variables
- [x] Your code contains different functions, so that is nice also handy to reuse the functions 👌
- [x] Map/for each are being used in the correct way
- [x] A lot of improvements are made, it is nice to see your code progress and what you did differently than last time

## Quick summary:

Your repo & wiki is looking good you have most of the thing available within your repo, just make sure to fill up the white space where possible (so it doesn't seem blank). Also nice to see your progress keep that up! I think you can now begin with the RDW datasets to make one dataset that contains all your needed data :)

Keep it up, hopefully, my feedback is something useful (☞ﾟヮﾟ)☞☜(ﾟヮﾟ☜)

**Comment by ralfz123** [comment]
Thanks Rowin!
Wat bedoel je met "Functional patterns that are being used is missing in the documentation"? De filter en map enz? Die staan [hier](https://github.com/ralfz123/functional-programming/wiki/Clean-data).

_ Data is described properly, you are just missing that you are doing with invalid and empty values_ --> wat bedoel je hiermee? Wat mis ik?

Voor de rest, super bedankt man!
Lekker helder en heb ik zeker wat aan, thanks!

**Comment by RowinRuizendaal** [comment]
> 
> 
> Thanks Rowin!
> Wat bedoel je met "Functional patterns that are being used is missing in the documentation"? De filter en map enz? Die staan [hier](https://github.com/ralfz123/functional-programming/wiki/Clean-data).
> 
> _ Data is described properly, you are just missing that you are doing with invalid and empty values_ --> wat bedoel je hiermee? Wat mis ik?
> 
> Voor de rest, super bedankt man!
> Lekker helder en heb ik zeker wat aan, thanks!

Hey,

Ik denk dat ik in de war ben gebracht door je readme aangezien je daar een link hebt staan met de anchorlink : Functional Programming Patterns die naar je wiki linkte, maar die was voorheen leeg dus ik ging er van uit dat het daar genoteerd zou moeten zijn :).

onder het beoordelingskopje:

scan the repo + readme staat er een bullet van -> data used described properly? (what's done with invalid and empty values?)

dus eigenlijk in andere woorden wat doe je met de values die bijvoorbeeld NULL/ ' ' zijn, het zelfde wat je zeg maar [hier](https://github.com/ralfz123/functional-programming/wiki/Clean-data#filter-een-lijst-met-correct-ingevoerde-namen-zonder-viezigheid) doet, ik wist alleen echter niet of dat ook in je README moest staan om te laten zien waar je rekening mee gehouden hebt voor eventueel een andere programmeur :D of als je andere datasets er in gaat verwerken, dat ze weten dat sommige datapunten NULL worden.
