### ISSUE TITLE
Feedback hoofdvraag

### ISSUE THREAD

**Issue by chelseadoeleman** [ralfz123/functional-programming#6]
Hi Ralf!

Nice, lekker bezig! Misschien zou je de hoofdvraag nog kunnen herformuleren om er een lopende zin van te maken. Wel super interessant om te onderzoeken 😊. Ik heb echt geen idee, maar kun je in de dataset vinden wanneer de parkeergarages sluiten of ga je hiervoor een externe dataset gebruiken?

**Comment by ralfz123** [comment]
Hi Chelsea!
Dankjewel voor je feedback!

Ja de hoofdvraag ga ik zeker nog concreter opschrijven, die is nu nog wat breed.
Sluitingstijden van parkeergebieden heb ik ergens voorbij zien komen ja. Anders zal ik hiervoor een externe dataset voor moeten gebruiken.
Maar als dat mission impossible wordt, dan haal ik dat van de avondtijden er misschien uit
